# Generated by Django 4.0.1 on 2022-01-18 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_number', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=200)),
                ('price', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('buying_price', models.IntegerField(default=0)),
                ('resell_price', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('restock_level', models.IntegerField(default=0)),
                ('date_acquired', models.DateField(auto_now_add=True)),
                ('date_restocked', models.DateField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikes.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SpareSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('date_sold', models.DateField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikes.employee')),
                ('spare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.spare')),
            ],
        ),
        migrations.CreateModel(
            name='RentBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id', models.CharField(max_length=200)),
                ('renter_name', models.CharField(max_length=200)),
                ('rent_period', models.IntegerField(choices=[(1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours'), (4, '4 Hours'), (5, '5 Hours'), (6, '6 Hours'), (7, '7 Hours'), (8, '8 Hours'), (9, '9 Hours'), (10, '10 Hours'), (11, '11 Hours'), (12, '12 Hours')])),
                ('bike_rent_rate', models.IntegerField(default=0)),
                ('time_left', models.DateTimeField(auto_now_add=True)),
                ('time_returned', models.DateTimeField(auto_now=True)),
                ('returned_condition', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=200)),
                ('total_charge', models.FloatField(default=0)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.employee')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikes.employee'),
        ),
    ]
