# Generated by Django 4.0.2 on 2022-02-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentBike',
            new_name='Rental',
        ),
        migrations.RemoveField(
            model_name='sparesale',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='sparesale',
            name='spare',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
        migrations.DeleteModel(
            name='SpareSale',
        ),
    ]
