# Generated by Django 4.0.2 on 2022-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_rename_rentbike_rental_remove_sparesale_sold_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rental_rate',
            field=models.FloatField(default=0),
        ),
    ]
