# Generated by Django 4.0.2 on 2022-02-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bike_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='total_charge',
            new_name='damage_fee',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='rent_period',
            new_name='rental_period',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='bike_rent_rate',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='renter_name',
        ),
        migrations.AddField(
            model_name='rental',
            name='overtime_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_charged',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='availability',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], default='1', max_length=200),
        ),
    ]
