# Generated by Django 4.0.2 on 2022-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_rename_total_charge_rental_damage_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Male', max_length=200),
        ),
    ]
