# Generated by Django 4.0.2 on 2022-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_hub_bike_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
