# Generated by Django 4.0.2 on 2022-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_hub_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='location',
        ),
        migrations.AddField(
            model_name='hub',
            name='latitude',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='longitude',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
